'use strict';

// Regenerate lib/assets.js from the source fonts + photo in assets-src/.
// Run after changing the speaker photo or fonts:
//   node scripts/build-assets.js

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'assets-src');
const b64 = (p) => fs.readFileSync(p).toString('base64');

const fonts = {
  m700: b64(path.join(SRC, 'fonts/montserrat-700.woff')),
  m800: b64(path.join(SRC, 'fonts/montserrat-800.woff')),
  m900: b64(path.join(SRC, 'fonts/montserrat-900.woff')),
  r500: b64(path.join(SRC, 'fonts/manrope-500.woff')),
  r600: b64(path.join(SRC, 'fonts/manrope-600.woff')),
  r700: b64(path.join(SRC, 'fonts/manrope-700.woff')),
};
const photo = b64(path.join(SRC, 'expert.jpg'));

let out = "'use strict';\n";
out += '// Auto-generated by scripts/build-assets.js — do not edit by hand.\n';
out += '// Fonts (woff) and speaker photo inlined as base64 so the renderer needs\n';
out += '// no external files (safe for serverless bundling).\n\n';
out += "const B = (s) => Buffer.from(s, 'base64');\n\n";
for (const [k, v] of Object.entries(fonts)) out += `const ${k} = '${v}';\n`;
out += '\nmodule.exports = {\n  fonts: {\n';
out += '    montserrat700: B(m700), montserrat800: B(m800), montserrat900: B(m900),\n';
out += '    manrope500: B(r500), manrope600: B(r600), manrope700: B(r700),\n';
out += '  },\n';
out += `  photoDataUri: 'data:image/jpeg;base64,${photo}',\n`;
out += '};\n';

fs.writeFileSync(path.join(ROOT, 'lib/assets.js'), out);
console.log('lib/assets.js regenerated (', out.length, 'chars )');
